name: proompt

services:
  proompt:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.24"
        ALPINE_VERSION: "3.21"
    
    image: proompt:latest
    container_name: proompt-server
    hostname: proompt-server
    
    ports:
      - "8080:8080"
    
    environment:
      - PROOMPT_SERVER_HOST=0.0.0.0
      - PROOMPT_SERVER_PORT=8080
      - PROOMPT_DB_TYPE=local
      - PROOMPT_DB_PATH=/app/data/proompt.db
      - PROOMPT_DB_MIGRATIONS=/app/data/migrations
      - PROOMPT_STORAGE_REPOS_DIR=/app/data/repos
      - PROOMPT_LOG_LEVEL=info
    
    volumes:
      - proompt_data:/app/data
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    
    restart: unless-stopped
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    security_opt:
      - no-new-privileges:true
    
    user: "1001:1001"
    
    networks:
      - proompt_network

networks:
  proompt_network:
    driver: bridge
    name: proompt_net

volumes:
  proompt_data:
    driver: local
    name: proompt_data